import type { Metadata } from "next";
import "./globals.css";
import CustomCursor from "./components/CustomCursor";
import Menu from "./components/Menu";
export const metadata: Metadata = {
  title: "Eugene Fidelis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Menu />
        {children} <CustomCursor />
      </body>
    </html>
  );
}
